import torchvision.models as models
# 查看部分模型 的结构
resnet18 = models.resnet18()
alexnet = models.alexnet()
vgg16 = models.vgg16()
squeezenet = models.squeezenet1_0()
densenet = models.densenet161()
inception = models.inception_v3()
googlenet = models.googlenet()
shufflenet = models.shufflenet_v2_x1_0()
mobilenet = models.mobilenet_v2()
resnext50_32x4d = models.resnext50_32x4d()
print(resnet18)
print(alexnet)
print(squeezenet)
print(densenet)
print(inception)
print(googlenet)
print(shufflenet)